// <auto-generated />
using Dodo.EFDataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Dodo.EFDataAccess.Migrations
{
    [DbContext(typeof(DodoEFContext))]
    [Migration("20190516084511_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Dodo.Domain.Models.Todo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content");

                    b.Property<bool>("IsCompleted");

                    b.HasKey("Id");

                    b.ToTable("Todos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "0TestTestTestTest TestTest",
                            IsCompleted = false
                        },
                        new
                        {
                            Id = 2,
                            Content = "1TestTestTestTest TestTest",
                            IsCompleted = false
                        },
                        new
                        {
                            Id = 3,
                            Content = "2TestTestTestTest TestTest",
                            IsCompleted = false
                        },
                        new
                        {
                            Id = 4,
                            Content = "3TestTestTestTest TestTest",
                            IsCompleted = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
